name: Sync Proxies Folder

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  sync_proxies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config --global user.name "handeveloper1"
          git config --global user.email "oguzhanyazman@gmail.com"

      - name: Remove old folders
        run: |
          rm -rf Proxies-Ercin
          rm -rf Proxy-Zaeem20
          rm -rf Proxy-KangProxy
          rm -rf Proxy-mzyui
          rm -rf Proxy-TuanMinPay

      - name: Download proxies
        run: |

          mkdir -p Proxies-Ercin
          git clone --depth=1 https://github.com/ErcinDedeoglu/proxies.git temp_repo
          mv temp_repo/proxies/*.txt Proxies-Ercin/ || true
          rm -rf temp_repo

          mkdir -p Proxy-Zaeem20
          curl -L https://raw.githubusercontent.com/Zaeem20/FREE_PROXIES_LIST/master/https.txt -o Proxy-Zaeem20/https.txt

          mkdir -p Proxy-KangProxy
          curl -L https://raw.githubusercontent.com/officialputuid/KangProxy/KangProxy/https/https.txt -o Proxy-KangProxy/https.txt

          mkdir -p Proxy-mzyui
          curl -L https://raw.githubusercontent.com/mzyui/proxy-list/main/http.txt -o Proxy-mzyui/http.txt

          mkdir -p Proxy-TuanMinPay
          curl -L https://raw.githubusercontent.com/TuanMinPay/live-proxy/master/http.txt -o Proxy-TuanMinPay/http.txt

      - name: Show downloaded files
        run: |
          echo "FILES:"
          ls -R

      - name: Commit and push
        run: |
          git add .
          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi

          git commit -m "Updated proxies $(date)"
          git pull --rebase origin main || true
          git push
